import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
import { AuthProvider } from "@/components/AuthProvider"; // <– nuevo import



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-white text-black"
      >
        <AuthProvider>
         <Navbar></Navbar>
         <main className="max-w-7xl mx-auto px-6 py-10">
          
          {children}
         </main>
        </AuthProvider>
      </body>
    </html>
  );
}
